### ISSUE TITLE
"@get gold_pick" crashes the game

### ISSUE THREAD

**Issue by Easyidle123** [gaucho-matrero/altoclef#109]
Running "@get gold_pick" causes a crash.

Two examples:
[crash-2021-10-07_18.33.32-client.txt](https://github.com/gaucho-matrero/altoclef/files/7307635/crash-2021-10-07_18.33.32-client.txt)
[crash-2021-10-07_18.35.36-client.txt](https://github.com/gaucho-matrero/altoclef/files/7307636/crash-2021-10-07_18.35.36-client.txt)

**Comment by adrisj7** [comment]
Should be fixed in above commit
