### ISSUE TITLE
Bot spams containers until stack is drained if no container nearby at start

### ISSUE THREAD

**Issue by Easyidle123** [gaucho-matrero/altoclef#111]
## Description
When trying to use a container to perform an action (craft, smelt, etc), if the bot has not placed and used one in the area and has multiple it will spam place them until its stack is empty or dropped.

## Steps to reproduce
1. Make a new world
2. Give yourself 64 crafting tables and 8 cobblestone
3. run @get furnace

## Expected Behavior
The bot places a crafting table and makes a furnace

## Actual Behavior
The bot places crafting tables whenever it can until the stack runs out or is dropped, and then makes the furnace with the last container.

This also causes the issue of the bot soft-locking the player if used in creative mode, as with infinite blocks it can never run out.

## Crashlogs and Screenshots (if applicable)
![Example](https://user-images.githubusercontent.com/26750005/136621613-c08e2a33-4dce-45a9-bdb4-024810474788.png)

**Comment by adrisj7** [comment]
I think this was fixed with https://github.com/gaucho-matrero/altoclef/pull/95, should be in the latest release now.
