### ISSUE TITLE
Perfect fall save/MLG

### ISSUE THREAD

**Issue by adrisj7** [gaucho-matrero/altoclef#118]
## Your Idea
- Make general bucket MLG rock solid (as long as the ground is MLG-able, it should be able to MLG from any orientation)
- Add hay + bed MLG if available (bed might not be as doable)
- Add nether vine MLG, where bot moves itself to the center of a block mid air if it can move in that direction

**Comment by JamesGreen31** [comment]
added

**Comment by adrisj7** [comment]
damn didn't even notice
