### ISSUE TITLE
No deepslate ores

### ISSUE THREAD

**Issue by scouttiger** [gaucho-matrero/altoclef#122]
## Bug Description
The bot only checks for normal ores, not the deepslate ores.

## Expected Behavior
The bot checking for both deepslate and normal stone ores.

## Actual Behavior
only checks normal stone ores, not deepslate

**Comment by adrisj7** [comment]
I'm unable to replicate this, it seems like the bot handles deepslate ores when running things like `get iron_ingot` or `get diamond`. Is there a reproducible command or video you can show where this happens?

**Comment by adrisj7** [comment]
I think this was probably on the release and not nightly (yay me for not keeping things up to date), I believe this has been fixed.
