### ISSUE TITLE
Gear gatherer

### ISSUE THREAD

**Issue by scout247** [gaucho-matrero/altoclef#123]
## Your Idea
A command or placeholder to be able to let the bot get full gear (netherite tools and all tools + sword) 
for example: @get diamond_gear or #netherite_gear. This would make the bot more usefull on Anarchy servers.

**Comment by walksanatora** [comment]
tbh i think this should be smth more like @gear so ex:
@gear leather
@gear gold
@gear iron
@gear diamond
@gear netherite
which would get you full armor/tools of that level

**Comment by scouttiger** [comment]
that could indeed be the command aswell. Would be nice to have imo

**Comment by JamesGreen31** [comment]
This issue is resolved
command is now @equip
