### ISSUE TITLE
Update baritone 

### ISSUE THREAD

**Issue by DarkReaper231** [gaucho-matrero/altoclef#128]
There is new branch of baritone from wagyourtail
You might want to switch to this new branch since I don't think Meteor will continue using their fork. 
 
https://github.com/wagyourtail/baritone/tree/1.17.1

Also wagyourtail's branch is really likely to be merged into baritone repo when leijurv feels like so

**Comment by DarkReaper231** [comment]
Wouldn't you know it wagyourtail's fork got included into baritone repo. So there is official 1.17.1 version of baritone

https://github.com/cabaletta/baritone/tree/1.17.1

**Comment by adrisj7** [comment]
I think I took care of this when merging 1.17.1 baritone
