### ISSUE TITLE
switches endlessly between food and sword

### ISSUE THREAD

**Issue by DdaannnRU** [gaucho-matrero/altoclef#130]
## Bug Description
switches endlessly between food and sword
## Steps to Reproduce (as best as you can)
bring @gamer to the blaze killing stage
## Expected Behavior
use sword OR eat food
## Actual Behavior
endless switching between food and sword
## Crashlogs and Screenshots (if applicable)
https://youtu.be/L1ETM2eHtlY
_(you may drag + drop text logs and images here, thanks GitHub)_

**Comment by adrisj7** [comment]
Looks like it's getting stuck because there's something in the cursor stack, good edge case catch!

**Comment by SylveonBottle** [comment]
Same seems to happen when low on health/food and attempting to run away from zombies while trying to eat.
Actually, for some reason this absolutely tanks my FPS. And if it's a skeleton, Altoclef generally dies due to this lag.

**Comment by JamesGreen31** [comment]
Cursor stacks need a lot of work. This should fix on the next big refactor

**Comment by trillhc** [comment]
This seems to mainly happen if your inventory is full

**Comment by JamesGreen31** [comment]
Part of the problem may also be that the bot doesn't want to use the sword unless the config is set to DELAY.

**Comment by JamesGreen31** [comment]
This has been fixed

**Comment by JamesGreen31** [comment]
@adrisj7 resolve
