### ISSUE TITLE
bot gets stuck if nether portal is surrounded with soul sand

### ISSUE THREAD

**Issue by DdaannnRU** [gaucho-matrero/altoclef#133]
## Bug Description
bot gets stuck if nether portal is surrounded with soul sand
## Steps to Reproduce (as best as you can)
get nether portal build in soul biome
## Expected Behavior
go to the soul sand
## Actual Behavior
stucks at the portal 
## Crashlogs and Screenshots (if applicable)
https://youtu.be/uP67Ug0CTvY
_(you may drag + drop text logs and images here, thanks GitHub)_

**Comment by JamesGreen31** [comment]
This has been resolved @adrisj7 please resolve this
