### ISSUE TITLE
stuck on crafting

### ISSUE THREAD

**Issue by Zierdo** [gaucho-matrero/altoclef#137]
cant craft pickaxe

it gets stuck

craft pickaxe and beat game

gets stuck on crafting 
![Screenshot (80)](https://user-images.githubusercontent.com/62662060/145184853-c857b6fa-a00e-4df4-9409-5c5bb661a32e.png)

**Comment by adrisj7** [comment]
got any logs? that would make this easier.

**Comment by JamesGreen31** [comment]
In addition to logs, it looks like you have a few other mods applied since your crafting menu doesn't look normal. That could also cause an issue. Try running it with just altoclef and baritone
