### ISSUE TITLE
[Suggestion] Go back to the starting position when done

### ISSUE THREAD

**Issue by TheBlueBurger** [gaucho-matrero/altoclef#14]
If you for example mine diamonds, it will end the task underground when it's done.
It would be good to add a option to pathfind to the starting position when it is done.

**Comment by adrisj7** [comment]
Interesting idea.

Currently I have the option to run an "Idle" task when the bot is done.

In the future I might replace that with an option to run a "default" task which can include idling, going back to a start position, or something else (not sure what else but I'm sure there's something). Maybe use baritone's waypoint system to define a "home" or something like that?

**Comment by adrisj7** [comment]
Achievable with the new `idleCommand` variable. Set it to something like
`"idleCommand" : "goto X Z"`
