### ISSUE TITLE
Game crashes upon entering the End

### ISSUE THREAD

**Issue by WhatsWifi** [gaucho-matrero/altoclef#140]
## Bug Description
Sometimes, not always, when entering the end the game would freeze up and eventually crash randomly.

## Steps to Reproduce (as best as you can)
1. Load up a fresh world
2. Let the bot do its thing
3. When it reaches the end, cross your fingers and hope it happens

## Expected Behavior
The end loads

## Actual Behavior
The game crashes

## Crashlogs and Screenshots (if applicable)

Crash report >> [https://pastebin.com/1DHEdeH1](https://pastebin.com/1DHEdeH1)

Images >>
![image](https://user-images.githubusercontent.com/45213292/145338431-8261c91b-df3a-4e4b-9a3a-9cb9d41b1932.png)

**Comment by JamesGreen31** [comment]
I believe this is happening because the bot attempts to execute that task before the block is loaded. 

I have applied a fix to my branch and will push it as a bugfix patch in the future

**Comment by JamesGreen31** [comment]
I fixed it. Pull Request # 158 resolves this issue
