### ISSUE TITLE
Baritone endlessly walks around when bridging to fortress

### ISSUE THREAD

**Issue by WhatsWifi** [gaucho-matrero/altoclef#141]
## Bug Description
When needed to bridge to the nether fortress, baritone would place a few blocks, then endlessly walk around the tower, and sometimes get up it. (try updating baritone?)

## Steps to Reproduce (as best as you can)
1. Load up a fresh world
2. Let the bot do its thing
3. If the bot has to bridge to get to the nether fortress, it will place 5-8 blocks before jumping down/going back and looping to the end of the bridge and back

## Expected Behavior
It bridges all the way to the fortress or finds another way to get there.

## Actual Behavior
It gets stuck i guess..?

## Crashlogs and Screenshots (if applicable)
Wasn't able to get any and don't have time to let it do its thing again. sorry

**Comment by adrisj7** [comment]
Screenshots would be helpful since it would help me figure out whether it was baritone that messed up or altoclef that interrupted baritone or something. Do you remember if there were any debug logs/flashing updates in the top left task chain display?

Updating baritone is a good idea.

**Comment by adrisj7** [comment]
Currently updating baritone, as this doesn't have test cases/videos I'll close it

**Comment by WhatsWifi** [comment]
Sorry I wasn't able to recreate it despite the fact that it happened like 3 times in one day.
