### ISSUE TITLE
Run away from creeper

### ISSUE THREAD

**Issue by Neruxov** [gaucho-matrero/altoclef#142]
From many tries (beating the game), the bot is mainly dying because of creepers, so it would be a good idea to make bot run away from creepers.

**Comment by serainox420** [comment]
> From many tries (beating the game), the bot is mainly dying because of creepers, so it would be a good idea to make bot run away from creepers.

Code? Where?

**Comment by adrisj7** [comment]
Bot already does that. Whether it's reliable is another issue, but your issue would need to be more descriptive.
