### ISSUE TITLE
Pick up items on death that will be used in future

### ISSUE THREAD

**Issue by Neruxov** [gaucho-matrero/altoclef#143]
It would be cool that bot will pick up items on death which will be used later, for example beds, but it only picks up tools and armor.

**Comment by JamesGreen31** [comment]
I think this was fixed now. If not though, it is a planned re-work of the get items task. As it is likely already done, or is planned, I am closing the issue.

**Comment by JamesGreen31** [comment]
I think this was fixed now. If not though, it is a planned re-work of the get items task. As it is likely already done, or is planned, I am closing the issue.
