### ISSUE TITLE
Bot Dies often in Gamer run when trying to beat game

### ISSUE THREAD

**Issue by JaserTech** [gaucho-matrero/altoclef#145]
During a run to beat the game, the bot dies often to skeletons, which it ignores unless they are within range of sword.

Also, when it died, and its stuff was at the bottom of a hole, it keeps going back to hole and falling and dyeing over and over trying to get its stuff back

**Comment by JaserTech** [comment]
Maybe when it is retrieving stuff from death it should check if there is a drop, and create appropriate mlg methods so it won't die

**Comment by AvinchYoshinova** [comment]
.minecraft/altoclef/altoclef_settings.json

"killAnnoyingHostileWhenCloseForSeconds" : 5.0

**Comment by JamesGreen31** [comment]
I think that the issue "fails to get dropped itsms" suits this issues title better than it dies often. However, we do plan to do some major re-works. Given the age of this issue report, im going to close it. I will keep the community updated on improvements to the bots survivability in the discord and on git when appropriate.
