### ISSUE TITLE
Autoclef crashes when joining some servers

### ISSUE THREAD

**Issue by JamesGreen31** [gaucho-matrero/altoclef#147]
So I am unable to host even a plan server because I get 
![image](https://user-images.githubusercontent.com/72313560/147047685-0c63cbd2-0628-4f70-b9fb-6dd3317e355a.png)

Also, it gets stuck in a loop after looking for the stronghold. I cannot get to the dragon because it thinks the stronghold is in the nether.

**Comment by DdaannnRU** [comment]
It is trying to build a portal right to the stronghold, but fails.

**Comment by JamesGreen31** [comment]
This turned out to be an issue with my Minecraft instances. It's complicated, but in any case im closing the issue
