### ISSUE TITLE
Potential error in help files?

### ISSUE THREAD

**Issue by SylveonBottle** [gaucho-matrero/altoclef#148]
https://github.com/gaucho-matrero/altoclef/blob/22e9212149c4d5f36eb461c44b0ef8e0af3d17e5/src/main/java/adris/altoclef/Settings.java#L84

help info for `foodUnitsToCollect` mentions a `foodUnitsThreshold`, however no such thing exists.
Is this meant to say `minimumFoodAllowed`?

```
    /**
     * minumum amount of food to have in the inventory.
     * if we have less food than this value the bot will go pickup some more.
     */
    private int minimumFoodAllowed = 0;


    /**
     * amount of food to collect when the food in inventory
     * is lower than the value of minimumFoodAllowed 
     */
    private int foodUnitsToCollect = 0;
```

**Comment by JamesGreen31** [comment]
Yes, good catch. _foodUnitsThreshold_ is the "minimumFoodAllowed". If you are lower than the amount of minimum food allowed, then the bot will aquire [foodUnitsToCollect].

**Comment by adrisj7** [comment]
Good catch, you are correct!
