### ISSUE TITLE
Bot switches between 2 items really quickly in furnace

### ISSUE THREAD

**Issue by TheBlueBurger** [gaucho-matrero/altoclef#15]

**Comment by adrisj7** [comment]
Yeah, I know. As far as I know this has no impact on its ability to smelt so it's no biggie. Might fix this later though, should be simple.

**Comment by adrisj7** [comment]
sadge, looks like my furnace changes might have fixed this one :(

At least we still have bear strats.

rest in piece furnace fuel switching, you will be missed.
