### ISSUE TITLE
I can't play game with ImmersivePortalsMod

### ISSUE THREAD

**Issue by ffffffffawd** [gaucho-matrero/altoclef#154]
## Bug Description
The Alto Clef with the ImmersivePortalsMod in activating the portal, game is work. But  I'm try to rejoin my save the game is collapse 
## Steps to Reproduce (as best as you can)
Install the Alto Clef Mod with Baritone Mod and ImmersivePortalsMod, Then activate the portal, You can see the protal is activated,is work. But in you rejoin or restart to save, The game is collapse
## Crashlogs and Screenshots (if applicable)
_(you may drag + drop text logs and images here, thanks GitHub)_
[crash-2021-12-28_19.31.01-client.txt](https://github.com/gaucho-matrero/altoclef/files/7788650/crash-2021-12-28_19.31.01-client.txt)

**Comment by JamesGreen31** [comment]
What does the immersive portals mod do?

**Comment by ffffffffawd** [comment]
Add a Breaks
[#943](github.com/qouteall/ImmersivePortalsMod/issues/943)

**Comment by ffffffffawd** [comment]
He just say:"I'm added breaks, next ver Fabric can display not compatible."
Holy ****

**Comment by ffffffffawd** [comment]
He in now reply me say:" Hope it's smaller. Closed due to duplication with [#933](https://github.com/qouteall/ImmersivePortalsMod/issues/933).

**Comment by ffffffffawd** [comment]
So the Alto-Clef can or cannot fix this bug?

**Comment by adrisj7** [comment]
Immersive portals make massive changes to how nether portals work and I wasn't able to recognize an altoclef class from the bug report, so I don't think I can fix this one. It also could be a mod installation bug.

I will close this, if new information is found feel free to reopen if you can/make another report.
