### ISSUE TITLE
Bot occasionally tries to hot tub in the lava

### ISSUE THREAD

**Issue by JamesGreen31** [gaucho-matrero/altoclef#155]
## Bug Description

Bot will occasionally dig straight down into lava

## Steps to Reproduce (as best as you can)

Not 100% how to reproduce this. When my bot did it, it was in an attempt to build a nether portal in the overworld and it was trying to get to a location. It is very possible that the block it broke was adjacent to lava, but it looked like it dug straight into it.

## Expected Behavior
Bot should avoid the lava and path to avoid digging into where it would fall. 

## Actual Behavior
Dug straight into it and got stuck (it did get out of it though)

## Crashlogs and Screenshots (if applicable)
_(you may drag + drop text logs and images here, thanks GitHub)_

I don't have these as it didn't crash and I didn't have time to screenshot.

**Comment by JamesGreen31** [comment]
This is a minor bug as bot can escape easily.

**Comment by adrisj7** [comment]
Should have been fixed a while back (moving if it's standing on the block it's trying to destroy and it's dangerous below)
