### ISSUE TITLE
Bot cannot reach fast travel in nether if the portal is over a lava lake

### ISSUE THREAD

**Issue by JamesGreen31** [gaucho-matrero/altoclef#157]
## Bug Description

Bot cannot reach the fast travel coordinates if the portal is over a lava lake

## Steps to Reproduce (as best as you can)

Launch seed 4303161440386341421 and manually construct a nether portal near spawn.
Provide the bot the following items:
128 cobblestone
diamond gear (must manually equip)
ender eyes x64
ender pearls x16
obsidian x10
water
flint and steel.
food (x64)

## Expected Behavior

Bot reaches coordinates

## Actual Behavior

Bot will build out over the portal coordinates, but cannot build down so it gets stuck. If bot does not have enough cobblestone, it cannot build out at all.

## Crashlogs and Screenshots (if applicable)
_(you may drag + drop text logs and images here, thanks GitHub)_

![image](https://user-images.githubusercontent.com/72313560/147706105-f799fd93-2609-43d8-9c31-a1bf06bd2710.png)

I added a fix to ensure that it has enough cobblestone to build out to the mark, but it cannot build down.

## Altoclef version
Using the nightly release that was the latest release as of 12/29/2021. No additional modifications other than what was described (cobble stone fix)

**Comment by JamesGreen31** [comment]
This is a major bug

**Comment by JamesGreen31** [comment]
See pull request #159

**Comment by adrisj7** [comment]
> See pull request #159

Looks like James got this one! Please reopen if it appears again
