### ISSUE TITLE
Bot gets stuck when looking for sheep

### ISSUE THREAD

**Issue by JamesGreen31** [gaucho-matrero/altoclef#160]
## Overview
**Originally posted by aidenthebear2 from the Altoclef discord**

When the nightly bot can't find a sheep or a village
it just sits there
Give it the ability to wander around on land

## Steps to Reproduce (as best as you can)

It is unkown what causes this, but you can try disabling mob spawns and load a flat world. See if it wanders or gets stuck.

## Expected Behavior

Bot begins to wander until it finds a chunk that contains a sheep or a village.

## Actual Behavior (What lead to the bot getting permanently stuck)

Bot stands there 

## Crashlogs and Screenshots (if applicable)
_(you may drag + drop text logs and images here, thanks GitHub)_

![image](https://user-images.githubusercontent.com/72313560/147712890-9279c672-4f3b-478d-b9ce-513ef0daff7a.png)

## Altoclef version:
The nightly build (up to date as of 12/2021)

**Comment by adrisj7** [comment]
Line to fix is probably here: https://github.com/gaucho-matrero/altoclef/blob/dec0a409ffc83eb87f3599cab89a2e53f47e7822/src/main/java/adris/altoclef/tasks/entity/AbstractDoToEntityTask.java#L67
and maybe here, unsure if this ever happens though: https://github.com/gaucho-matrero/altoclef/blob/dec0a409ffc83eb87f3599cab89a2e53f47e7822/src/main/java/adris/altoclef/tasks/entity/AbstractDoToEntityTask.java#L112

**Comment by JamesGreen31** [comment]
Made changes suggested by @adrisj7 . These fixed the issue.

See pull request #162.

**Comment by adrisj7** [comment]
Merged in
