### ISSUE TITLE
On a 1.12.2 or lower server, it looks for raw ore which does not exist

### ISSUE THREAD

**Issue by Dabaski** [gaucho-matrero/altoclef#161]
## Your Idea

In @gamer during the process of beating the game it looks for and mines iron ore. It specifically looks for RAW_IRON and continues mining iron ore looking for raw_iron when it does not exist in earlier versions of minecraft. I discovered this issue when I was testing this on a local 1.12.2 server. If the pickaxe has silk touch this issue will also occur

Add the feature to both use iron_ore and raw_iron with @gamer instead of only raw iron.

**Comment by JamesGreen31** [comment]
As fun as it may be to upgrade altoclef to run on very outdated versions, I don't think this will happen given our current difficulty in keeping it updated.
