### ISSUE TITLE
Bot occasionally gets stuck when travelling with "goto block"

### ISSUE THREAD

**Issue by JamesGreen31** [gaucho-matrero/altoclef#165]
## Steps to Reproduce (as best as you can)
Load seed: -4663778002446194425
Build nether portal at 52 32 171
Provide bot everything it needs to start the fast travel sequence (locating end fortress)

## Expected Behavior
Bot should move to correct location

## Actual Behavior (What lead to the bot getting permanently stuck)
Bot gets stuck in a loop

This happens in both the fast travel sequence and the place bed sequence for this seed.

## Crashlogs and Screenshots (if applicable)
_(you may drag + drop text logs and images here, thanks GitHub)_

https://user-images.githubusercontent.com/72313560/147777318-3added26-4efe-432d-911e-b5e4b0c0f1e4.mp4

**Comment by JamesGreen31** [comment]
I believe this happens when the destiniation block is outside of the render distance as my render distance was 10 blocks but OPs was 10. Mine was able to path find quite well, but OPs got stuck on the basalt pillars to the left of portal exit while mine chose to approach the lava lake and then mine.

**Comment by adrisj7** [comment]
This is a "Stuck Check"/wander issue. Meloweh has a PR with better stuck detection that's baked into baritone https://github.com/gaucho-matrero/baritone/pull/2

It's currently a bit messy with the merging (would need to cherry-pick/redo some parts of the PR) but it should fix these edge cases.

**Comment by JamesGreen31** [comment]
this fixedyet?

**Comment by adrisj7** [comment]
don't know, this is a big edge case that's hard to check for. As far as I know it still _could_ happen but it's extremely rare and fixing it optimally is a bit of a pain

**Comment by JamesGreen31** [comment]
Going to assume it's good now and close the issue. If it pops up again, I'll remake it.
