### ISSUE TITLE
The ability to hide/reduce the text that appears in the top right corner

### ISSUE THREAD

**Issue by Dabaski** [gaucho-matrero/altoclef#169]
## Your Idea
A good way to reduce clutter on the screen would a @hidetext or a @displaydebug <true/false>

**Comment by adrisj7** [comment]
Top right? What text? The only text we display is the task chain in the top left corner.

**Comment by Bluscream** [comment]
> ## Your Idea
> A good way to reduce clutter on the screen would a @hidetext or a @displaydebug <true/false>

`.minecraft\altoclef\altoclef_settings.json` -> `"showTaskChains" : false,`
