### ISSUE TITLE
Game Crash 

### ISSUE THREAD

**Issue by WindowsRefundDay** [gaucho-matrero/altoclef#170]
## Steps to Reproduce (as best as you can)
Have
- Altoclef-1.10-SNAPSHOT.jar
- baritone-api-fabric-1.18-SNAPSHOT.jar (from https://github.com/gaucho-matrero/baritone)
- EMC-F-v2-latest-1.18.1.jar
- Optifabric.jar (With Optifine in /mods)
Launch in Aristois 1.18
## Expected Behavior
Game should Boot Up to tittle screen
## Actual Behavior (What lead to the bot getting permanently stuck)
Game Crashed
## Crashlogs and Screenshots (if applicable)
_(you may drag + drop text logs and images here, thanks GitHub)_
[latest.log](https://github.com/gaucho-matrero/altoclef/files/7798345/latest.log)

Sorry for not much detail, I'm not a programmer :)

**Comment by adrisj7** [comment]
Thanks a ton for telling us what versions you're using, I should edit the template to include that.

You're using baritone 1.18, at the time of this bug only 1.17 is supported, and altoclef comes with its own baritone version which is required. If you don't use the one that's packaged with the release, it won't work.

I'll close this for now but if anything else pops up feel free to reopen/post another issue.

**Comment by WindowsRefundDay** [comment]
Ok, thanks! :D
