### ISSUE TITLE
Bot Collects Pearls from Piglins rather than Endermen in Warped Forest Biome

### ISSUE THREAD

**Issue by sam86314** [gaucho-matrero/altoclef#180]
## Your Idea

During the "getting ender pearls" step of a gamer run, I frequently find that the bot is trading with piglins in a warped forest biome, which spawns endermen very frequently. This ends up wasting time as there are usually many endermen in close proximity that could be killed for a much higher pearl drop rate.

## Suggested Behavior

Bot should prioritize killing endermen for pearls over piglin trading when in a warped forest biome.

## Actual Behavior

Bot continues to trade with piglins for pearls while in a warped forest despite many endermen being in close proximity.

**Comment by JamesGreen31** [comment]
This is actually a WIP. If you like, dm me on discord and I will send you the snapshot.

**Comment by adrisj7** [comment]
Implemented in latest beta build, configurable.
