### ISSUE TITLE
Question: Lowering the completion time for beating the game

### ISSUE THREAD

**Issue by trillhc** [gaucho-matrero/altoclef#193]
I was just wondering if anyone is working on the gamer command to get the bots to finish faster. If not I was thinking of taking that on as a side project. Any thoughts? If this should be asked somewhere else please let me know. Thanks!

**Comment by adrisj7** [comment]
Currently me and @JamesGreen31 have been making changes to `@gamer`, if you want to join hop on to the discord, we sometimes discuss there!
