### ISSUE TITLE
Crash: java.lang.NullPointerException: Cannot read the array length because "<local2>" is null

### ISSUE THREAD

**Issue by TheBlueBurger** [gaucho-matrero/altoclef#198]
## Steps to Reproduce (as best as you can)
Run the gamer command and wait
## Expected Behavior
Does not crash
## Actual Behavior (What lead to the bot getting permanently stuck)
Crashes. [Place of error](https://github.com/gaucho-matrero/altoclef/blob/909a46f008696b92cac0cb854887f992068fed8c/src/main/java/adris/altoclef/util/ItemTarget.java#L97).
`Error: java.lang.NullPointerException: Cannot read the array length because "<local2>" is null`
## Crashlogs and Screenshots (if applicable)
_(you may drag + drop text logs and images here, thanks GitHub)_
[log.txt](https://github.com/gaucho-matrero/altoclef/files/7996275/log.txt)

**Comment by adrisj7** [comment]
Should be fixed by https://github.com/gaucho-matrero/altoclef/commit/8a62ab3ae41657cb8fd573bfa103a0e62cffd512
