### ISSUE TITLE
crafting is wierd

### ISSUE THREAD

**Issue by TheGamerGerman** [gaucho-matrero/altoclef#205]
## Steps to Reproduce (as best as you can)
Let it craft something and sometimes it happens

## Expected Behavior
normal craft

## Actual Behavior
cant rly craft

## Crashlogs and Screenshots (if applicable)
[latest.log](https://github.com/gaucho-matrero/altoclef/files/8007945/latest.log)

_(you may drag + drop text logs and images here, thanks GitHub)_

**Comment by adrisj7** [comment]
Should be fixed in nightly. I should add a thing for nightly/non nightly releases, but that's kinda borked right now. Will make a hotfix release probably.
