### ISSUE TITLE
bot gets stuck on azalea bushes

### ISSUE THREAD

**Issue by pinkcreeper100** [gaucho-matrero/altoclef#215]
## Steps to Reproduce (as best as you can)
be in a lush cave or an area with moss and azalea bushes
## Expected Behavior
bot recognises where azalea bushes are, and either walks around them or breaks them
## Actual Behavior
bot tries to walk straight through the bushes / gets stuck going round in circles on top of them

**Comment by KTibow** [comment]
baritone problem, not altoclef's.

**Comment by wagyourtail** [comment]
except it is kinda an alto problem because it's already patched on upstream. alto's baritone fork is just behind.
