### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by AvinchYoshinova** [gaucho-matrero/altoclef#219]
## Your Idea
Using 1.16.5 and the latest features only supports 1.17-1.18

I like to use other features on 1.16.5 but I can't

Maybe compatibility version 1.16-1.17?
Or just copy 1.17/1.18 features into 1.16

**Comment by Dabaski** [comment]
Multi compatible versions is on the table for possibility according to the discord server, but will not be implemented for a long time because of the poor success rate of altoclef. The contributors and the author are doing their best to duck-tape the bugs and get them fixed for the time being.

**Comment by AvinchYoshinova** [comment]
I only need task chain though

**Comment by AvinchYoshinova** [comment]
> Multi compatible versions is on the table for possibility according to the discord server, but will not be implemented for a long time because of the poor success rate of altoclef. The contributors and the author are doing their best to duck-tape the bugs and get them fixed for the time being.

I only need task chain though

**Comment by wagyourtail** [comment]
1.18 + https://github.com/Earthcomputer/multiconnect

**Comment by AvinchYoshinova** [comment]
> 1.18 + https://github.com/Earthcomputer/multiconnect

already have a via plugin and i can only use 1.16 for now

**Comment by wagyourtail** [comment]
> already have a via plugin and i can only use 1.16 for now

multiconnect allows you to connect to older servers from a newer client so I don't see how that would make that not work...
