### ISSUE TITLE
1.18 support

### ISSUE THREAD

**Issue by SuperIsakSwahn** [gaucho-matrero/altoclef#220]
Someone asked for 1.18 support and it got closed, so I did another one, simple.

**Comment by TheGamerGerman** [comment]
dude you can use altoclef on 1.18 and 1.18.1: https://github.com/gaucho-matrero/altoclef/releases

**Comment by AvinchYoshinova** [comment]
there's already 1.18 support wdym?

**Comment by SnivyLlama** [comment]
Lmao it already exists

**Comment by SuperIsakSwahn** [comment]
Whoever closed the previous request closed it without saying anything at all, so I decided to ask for 1.18 for them, so calm your tits lol

**Comment by AvinchYoshinova** [comment]
just download it from releases lmao
