### ISSUE TITLE
Initial Crafting Delay (Crafting Table, Planks and Sticks)

### ISSUE THREAD

**Issue by Kaihen0** [gaucho-matrero/altoclef#222]
## Steps to Reproduce
1. Bot reaches any tree.
2. Let the bot grab the wood.
3. Wait.

## Expected Behavior
Bot should immediately craft essential materials/blocks.

## Actual Behavior
Bot will not react until alto clef detects cursor stack.

**Comment by JamesGreen31** [comment]
@Kaihen0 

Can you show me what you mean with some screenshots or a video? I do see a little bit of "annoying" behavior where the bot may break several wooden logs before picking any up. Sometimes I see it switch trees before it finishes breaking. Occasioanlly, I do see it get stuck saying something along the lines of "attempting to place block at ...." but it just stands there. However, it always resolves itself in a few seconds. Is this what you are referring to?

**Comment by JamesGreen31** [comment]
Closing because lack of information.
