### ISSUE TITLE
Bot gets stuck in Powder Snow

### ISSUE THREAD

**Issue by Kaihen0** [gaucho-matrero/altoclef#224]
## Steps to Reproduce
Spawn in a snowy mountain and the bot may fall into powder snow.
## Expected Behavior
Bot should escape by going upwards to the surface.
## Actual Behavior
Bot reproduces the same type of jump as if the bot was on water, resulting in constant death if human inputs arent pressed.

**Comment by offbeat-stuff** [comment]
Probably need to merge upstream baritone

**Comment by JamesGreen31** [comment]
@adrisj7 As I recall from a conversation with wagyourtail, the snow thing is a baritone problem that they were working on. Do you know if this was finished? Did we ever merge this version of baritone into Altoclef?

**Comment by JamesGreen31** [comment]
Fixed
