### ISSUE TITLE
Can't find the right block it is looking for

### ISSUE THREAD

**Issue by CreeperNinjaYT** [gaucho-matrero/altoclef#230]
## Steps to Reproduce (as best as you can)
Play with the mods on 1.18.2 (Given Baritone & given altoclef)

## Expected Behavior
Runs normal, finds right blocks and can finish commands like @gamer and @get

## Actual Behavior (What lead to the bot getting permanently stuck)
Can not find any blocks, when @gamer, or @get is done, bot gets stuck wandering forever even though the necessary blocks are around them

**Comment by JamesGreen31** [comment]
This is a known issue and will be worked on when 1.18.2 becomes the top priority.

**Comment by JamesGreen31** [comment]
1.18.2 is no live.
