### ISSUE TITLE
Powder snow death

### ISSUE THREAD

**Issue by TheGamerGerman** [gaucho-matrero/altoclef#239]
## Steps to Reproduce (as best as you can)
Put the bot into a snow biom it will problaby happen

## Expected Behavior
Should break the powder snow and/or avoid it

## Actual Behavior
gets stuck in it and dies
## Crashlogs and Screenshots (if applicable)
_(you may drag + drop text logs and images here, thanks GitHub)_

### Discord username (if you want updates)
TheGamerGerman#9321

### Developer Notes (leave this blank)

_Difficulty_: **_N/A_**
_Estimated Time Required_: **_N/A_**

**Comment by JamesGreen31** [comment]
This is a baritone issue. We just need to update Altoclef's baritone. We will get to this.

**Comment by JamesGreen31** [comment]
This should be fixed now
