### ISSUE TITLE
Throw away unused items not working

### ISSUE THREAD

**Issue by TheGamerGerman** [gaucho-matrero/altoclef#240]
## Steps to Reproduce (as best as you can)
1Give the bot a full inv.
2.Do a miner task
## Expected Behavior
Should detect that his inventory is full and drop the stack not carry it around on the courser
## Actual Behavior
Spamms in chat courser stack is ben hold for to long.Will move back in inventory and does not drop it. 
## Crashlogs and Screenshots (if applicable)
_(you may drag + drop text logs and images here, thanks GitHub)_

### Discord username (if you want updates)
TheGamerGerman#9321
### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by emlm244** [comment]
This is also true on mining mass mining diamonds. To add on to it, the bot should be able to look through its inventory and determine what it needs and what it doesn't need for the job.

**Comment by JamesGreen31** [comment]
@emlm244 I think it does do this in a way. Can you give me more comprehensive steps to reproduce this because I don't see it happening in my game. A good example would be if you can find a task that does this without @gamer.

Pictures are also unspeakably valuable as it shows me the task chain.
