### ISSUE TITLE
Clutches

### ISSUE THREAD

**Issue by emlm244** [gaucho-matrero/altoclef#241]
## Your Idea
When getting iron it would get an extra 3 iron to craft a water bucket. This would severely help out on falling and taking damage and fighting the ender dragon. 
### Discord username (if you want updates)
THE VOID#0742
### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by TheGamerGerman** [comment]
It does. I think

**Comment by JamesGreen31** [comment]
@emlm244 TheGamerGerman is correct. The bot already has an MLG task once it gets a water bucket.
