### ISSUE TITLE
Eating in Nether often does simply not work

### ISSUE THREAD

**Issue by TheGamerGerman** [gaucho-matrero/altoclef#242]
## Steps to Reproduce (as best as you can)
Let the bot do the @gamer task (give him full dia food and all the other stuff) let him go in to the nether for killing blazes.
## Expected Behavior
Should eat as normal and not die from getting to low on health.
## Actual Behavior
It does not react to its hunger going down at all even if hes at 0 hunger and 0.5 hearths as example he still does not eat at all.
## Crashlogs and Screenshots (if applicable)
_(you may drag + drop text logs and images here, thanks GitHub)_

### Discord username (if you want updates)
TheGamerGerman#9321
### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by JamesGreen31** [comment]
I am going to need more information for this to determine what the issue is.
