### ISSUE TITLE
Water Swimming

### ISSUE THREAD

**Issue by emlm244** [gaucho-matrero/altoclef#246]
## Steps to Reproduce (as best as you can)
When trying to get a treasure chest under the sea it would hold shift to get it there. Or to a destination on the seas.
This will help 
## Expected Behavior
The bot will go down into the water just enough that the swimming animation can occur. 
## Actual Behavior (What lead to the bot getting permanently stuck)
floats in the water doing nothing. Or getting suffocated and dying. 
When dying the bot will try to retrieve it stuff but will die again and again and again.
## Crashlogs and Screenshots (if applicable)
_(you may drag + drop text logs and images here, thanks GitHub)_

### Discord username (if you want updates)
THE VOID#0742
### Developer Notes (leave this blank)

_Difficulty_: **_Impossible_**
_Estimated Time Required_: **_the lifespan of the universe...and beyond_**
Once development starts.

**Comment by JamesGreen31** [comment]
Edit: Scaled the project

I personally would love to have the bot be able to swim. However, the bot's movement abilities are handled mainly by Baritone and its goal setting process. Baritone is another mod that is externally developed from Altoclef. Swimming has been an issue for years and I doubt it will be fixed anytime soon. However, you can count on us to make swimming a possibility as soon as it becomes achievable with baritone.
