### ISSUE TITLE
Unable to clear trash spots in inventory

### ISSUE THREAD

**Issue by emlm244** [gaucho-matrero/altoclef#248]
## Steps to Reproduce (as best as you can)
When mining needs to throw away blocks that are not needed to mine to get other blocks that are higher.
Mines diamonds
Inventory full
Throws out useless items that are not needed.
Continues mining....
## Expected Behavior
Throws useless blocks away that will not get it closer to its objective.
## Actual Behavior
Sits there and keeps refreshing its inventory doing nothing.
## Crashlogs and Screenshots (if applicable)
_(you may drag + drop text logs and images here, thanks GitHub)_

### Discord username (if you want updates)
THE VOID#0742
### Developer Notes (leave this blank)

_Difficulty_: **_Easy_**
_Estimated Time Required_: **_about a week_**
Once development starts.

**Comment by KTibow** [comment]
could you upload a video of this happening? screen recording is built in to all major oses

**Comment by JamesGreen31** [comment]
Edit: Scaled project

This is an interesting bug. It should manage its inventory already, but if it is not doing so we need to address this. I understand if a video is out of reach, but it would really help me fix this faster if you could at least capture the issue for a good 15 seconds, then close the game. Grab the log file and send that to me. It is called "latest.log" wherever your logs output is. That will let me examine the task tree and find out why it is unable to throw away trash

I hypothesize that this has to do with the recent changes to the cursor slot, so it shouldn't be too difficult to fix this up.

Thank you @KTibow for helping me stay on top of the issues.

**Comment by JamesGreen31** [comment]
didn't mean to close

**Comment by JamesGreen31** [comment]
![image](https://user-images.githubusercontent.com/72313560/161365598-d5bf9d42-96cd-497b-a089-3a06a827358e.png)

This issue is caused by mining when all our items are protected. We intend to resolve this with chest features in future updates.

In the mean time, if this happens during gamer task, please let me know so we can optimize it to not occur.

**Comment by JamesGreen31** [comment]
Closed issue as this is not actively going to be resolved now.

**Comment by dolphin-cat** [comment]
it could have placed one of the stacks in the offhand and then pick up that one more diamond it needed to finish the task

**Comment by KTibow** [comment]
altoclef doesn't use the offhand in general right now
also, what if the user already has something like a totem in their offhand?

**Comment by JamesGreen31** [comment]
The idea here is that Altoclef only has so many inventory spots. When executing a task like `@gamer`, you need to protect certain inventory items, which decreases the size of your inventory. If you don't have enough slots, it will fail.

This is similar to telling the bot to get 50 cakes. It can't store all the ingredients prior to crafting, so it will fail there as well.

It is easy to build a check for this, but we plan on building a system where altoclef strategically uses chests to solve the issue.
