### ISSUE TITLE
Bot do 2 tasks to the infinity 

### ISSUE THREAD

**Issue by Wans22** [gaucho-matrero/altoclef#255]
Hi, when I do @gamer, it gives me the task: "<wander for infinity blocks> exploring" to infinity or "<wander for infinity blocks> getting unstuck from block"
With that, altoclef does not work (but baritone works well, I tested it), yet I tested the nightly and long term release version.  Altoclef only randomly walks to infinity.

## Crashlogs and Screenshots (if applicable)
_(you may drag + drop text logs and images here, thanks GitHub)_
No crashlog, 2 screenshots
![IMG_20220409_172310](https://user-images.githubusercontent.com/82324747/162580695-dddc4849-8bc8-4736-982f-9713461c9b12.jpg)
![IMG_20220409_172136](https://user-images.githubusercontent.com/82324747/162580722-ecb98871-3fa3-4604-a8f4-9bcadf442b34.jpg)

## Other mods (if applicable)
Nothing
### Discord username (if you want updates)
Wan_s²#2353

**Comment by AvinchYoshinova** [comment]
what version did you use?

**Comment by KTibow** [comment]
It explores for "Infinity" until it can find a block. On 1.18.2, the block finder is broken, so won't work. Because it believes it's making no progress, it tries to get unstuck from the block by moving randomly.

**Comment by KTibow** [comment]
The current version of Altoclef is made for 1.18.1.

**Comment by Wans22** [comment]
> The current version of Altoclef is made for 1.18.1.

okay so I'm waiting for version 1.18.2 :)
I'll come back if it still doesn't work in this next version, for now I'm closing the issue
Thanks
