### ISSUE TITLE
Altoclef crashes on launch

### ISSUE THREAD

**Issue by ll821301** [gaucho-matrero/altoclef#256]
altoclef commands crash the game entirely, and baritone commands just don't work. baritone works without altoclef installed, so its 100% a issue with your mod.

## Dev notes (added by James)

This is 100% caused by the 1.18.1 altoclef trying to interact with 1.18.2 baritone. The versions need to be the same. 

We may want to try and integrate our baritone version either into Altoclef, or add some kind of check that if the baritone version isn't what we expect, refuse to start. This will prevent these duplicate issues from getting mixed in with more pressing ones.

**Comment by ll821301** [comment]
[latest.log](https://github.com/gaucho-matrero/altoclef/files/8468439/latest.log)

**Comment by ll821301** [comment]
@

**Comment by ll821301** [comment]
@wagyourtail @adrisj7 @DieGo367 @QuadraticKid fix pls

**Comment by JamesGreen31** [comment]
Locked thread as this is not a discussion I am having. 1.18.2 is currently not compatible with Altoclef.
