### ISSUE TITLE
Crashes on newest version

### ISSUE THREAD

**Issue by TheGamerGerman** [gaucho-matrero/altoclef#259]
## Steps to Reproduce (as best as you can)
run any command 
## Expected Behavior
Should not crash
## Actual Behavior (What lead to the bot getting permanently stuck)
After a few seconds the game crashes
## Crashlogs and Screenshots (if applicable)
_(you may drag + dr
[latest.log](https://github.com/gaucho-matrero/altoclef/files/8500635/latest.log)
op text logs and images here, thanks GitHub)_

### Discord username (if you want updates)
TheGamerGerman#9321
### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by JamesGreen31** [comment]
Yea I mucked up the release somehow. I fixed it this morning and will make a new release in a few hours.

**Comment by JamesGreen31** [comment]
Fixed in 0.4.1a which replaced 0.4.1

Should be good to go now.
