### ISSUE TITLE
Alto Clef on forge

### ISSUE THREAD

**Issue by MinecrasfsftMan** [gaucho-matrero/altoclef#265]
## Your Idea
Alto Clef on forge.

### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by JamesGreen31** [comment]
This has been discussed many times and unfortunately, the conversion work needed is greater than the time or scope of the project. Unless someone takes up the burden of converting it themselves, altoclef is staying on fabric as it requires a near total code base re-write.

**Comment by MinecrasfsftMan** [comment]
> This has been discussed many times and unfortunately, the conversion work needed is greater than the time or scope of the project. Unless someone takes up the burden of converting it themselves, altoclef is staying on fabric as it requires a near total code base re-write.

It's alright. Although I'm not a mod developer, I have seen the struggles of rewriting a mod.
