### ISSUE TITLE
Bot tries to create Eye of Ender, but fails repeatedly.

### ISSUE THREAD

**Issue by wenca611** [gaucho-matrero/altoclef#279]
## Steps to Reproduce (as best as you can)
Bot tries to create Eye of Ender, but fails repeatedly.
Status: Getting blaze rods
@stop and @gamer didn't help
problem, even if he has free inventory(only blaze powders and ender pearls)
## Actual Behavior (What lead to the bot getting permanently stuck)
I don't know, maybe added effects?
## Crashlogs and Screenshots (if applicable)
_(you may drag + drop text logs and images here, thanks GitHub)_
![image](https://user-images.githubusercontent.com/52932787/174447524-cc188115-085f-45dd-8f98-b7e1ed3a34de.png)

### Developer Notes (leave this blank)

_Difficulty_: normal
_Estimated Time Required_: **__**
Once development starts.

**Comment by KTibow** [comment]
Try opening your inventory and messing around with the crafting grid.

**Comment by JamesGreen31** [comment]
I thought I fixed this issue. I will take a second look at this when I finish the task creator.

**Comment by JamesGreen31** [comment]
See issue #285 

Development is there. This issue is more complicated than it appears
