### ISSUE TITLE
Changing baritone settings in tasks and commands

### ISSUE THREAD

**Issue by Bobbyperson12** [gaucho-matrero/altoclef#280]
## Your Idea
Allow altoclef commands/tasks to change baritone settings on the fly. Something like "set allowSprint false; goto 5000 0; get food; set allowSprint true"
### Discord username (if you want updates)
Bobbyperson#0026
### Developer Notes (leave this blank)

_Difficulty_: **_N/A_**
_Estimated Time Required_: **_N/A**

Feature already exists.

**Comment by JamesGreen31** [comment]
"Goto" is already an altoclef command. I am a little confused by this one.


As for changing settings on the fly, you can manually do this by editing the config file and then doing @reload. 

However, you can change baritone settings on the fly using the baritone prefix '#'.

Example:

#freelook false

**Comment by Bobbyperson12** [comment]
I'll elaborate. 

If you're making a custom task, what if you want the bot to walk somewhere, but after doing task X (getting food) you want it to sprint again?

**Comment by JamesGreen31** [comment]
This isn't a bad idea, however it falls in the realm of the task creator. I'll note this for that project.
