### ISSUE TITLE
add command to get full enchanted nethorite Armor and tools

### ISSUE THREAD

**Issue by jaxhelp** [gaucho-matrero/altoclef#282]
## Your Idea
Add command to get full enchanted nethorite armor and tools
### Discord username (if you want updates)
jaxfry#6198
### Developer Notes (leave this blank)

_Difficulty_: **_Trivial/Impossible_**
_Estimated Time Required_: **_15minutes/not_gonna_happen_**

Getting full netherite and tools is easy. Enchanting them is not something altoclef is currently capable of handling. To do that, we would have to write a signifigant amount of code and rework several systems, especially if we were trading for books. 

Currently, Altoclef:
- has no idea how to use an enchanting table
- has no idea how to read experience level
- has no idea how to reliably obtain enough experience to enchant
- has no strategy for enchanting
- has no strategy for villager trading
- has no strategy for finding villages
- has no strategy for selecting enchantments
- has no ability to read enchantment levels

All in all, enchanting for the bot is sorta out of scope as the time reqruied to enchant would be almost exponential, but the benefit would be marginal. If the bot dies beacuse of no enchantments, it could have full netherite armor again in about an hour, with full diamond in about 5-10min.

Currently, you can run `@get[diamond_pickaxe 2];equip[diamond_helmet,diamond_chestplate,diamond_leggings,diamond_boots],get[diamond_pickaxe 3,diamond_shovel 1,diamond_sword 1];equip[netherite_helmet,netherite_chestplate,netherite_leggings,netherite_boots];get [netherite_pick 1];get[netherite_shovel 1,netherite_axe 1,netherite sword 1,netherite_hoe 1]` to get it for you. Here is a breakdwon

1. Get 2 diamond pickaxes
2. get and equip full diamond armor
3. Ensure we have 3 diamond picks and a diamond shovel (it will go through about 2 picks for netherite armor)
4. get and equip full netherite armor
5. get a netherite pickaxe
6. get netherite tools

if I spelled anything wrong you will have to fix it.

**Comment by JamesGreen31** [comment]
Alternatively, you can drop (after extracting) this file in the altoclef configs folder next to the beat minecraft config. Then when in game, run @custom bestgear

Please note that if you die in the nether, this task will probably break in terms of efficiency.
[CustomTasks.zip](https://github.com/gaucho-matrero/altoclef/files/8987357/CustomTasks.zip)

**Comment by JamesGreen31** [comment]
see previous comment
