### ISSUE TITLE
self-referential adris.altoclef.tasks.construction.compound.ConstructNetherPortalBucketTask.getNumberOfBlocksAdjacent(ConstructNetherPortalBucketTask.java:310)

### ISSUE THREAD

**Issue by yeetmanthecoolman** [gaucho-matrero/altoclef#291]
## Steps to Reproduce (as best as you can)
run @gamer and let the bot build a portal.
## Expected Behavior
builds portal
## Actual Behavior (What lead to the bot getting permanently stuck)
intantly crashes
## Crashlogs and Screenshots (if applicable)
_(you may drag + drop text logs and images here, thanks GitHub)_
[crash-2022-08-27_17.56.48-client.txt](https://github.com/gaucho-matrero/altoclef/files/9438806/crash-2022-08-27_17.56.48-client.txt)

## Other mods (if applicable)
lithium phosphor and sodium.
### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by JamesGreen31** [comment]
I believe this is a mod compatibility issue.

For now, we are only going to work on bugs for vanill minecraft+altoclef
