### ISSUE TITLE
这个视频非法使用您的项目

### ISSUE THREAD

**Issue by shangguanlingyu** [gaucho-matrero/altoclef#307]
https://www.bilibili.com/video/BV18d4y1c7wd
This is a video connection
He used your project to make videos without specifying the mod download address and the author
You must pay attention to the video publisher to download this mod through other channels

**Comment by JustaSqu1d** [comment]
The title reads "this video illegally uses your project" by the way.

Anyways, it doesn't because the license of this mod is preserved. The MIT license also gives users express permission to reuse code for any purpose, sometimes even if code is part of proprietary software. It's not illegal.

**Comment by beyond-dinosaur** [comment]
OK.Anyways,others can't use it to grew fat on illegal profits without permission.

**Comment by JustaSqu1d** [comment]
> OK.Anyways,others can't use it to grew fat on illegal profits without permission.

Actually, they can according to the MIT License.

**Comment by JamesGreen31** [comment]
Yea this is kinda why I tho u hit about switching the license to GPL3.0 or some of the similar. However, past builds are under the MIT license, so it's kinda moot at this point.

As long as people aren't making money off it, I'm probably not gonna switch the license.

@adrisj7 what do you think? Should we switch to a license that requires acknowledgement?

**Comment by JamesGreen31** [comment]
Note: MPL 2.0 is probably the best license for us. It lets people use the project however they want (including in closed source, for profit ventures), but also requires them to push changes to our upstream (or at least make them AV) so we can benefit from them.

Ofc, this is only the case if people actually adhere to licenses. I probably wouldn't pursue violators unless they were making bank.

The problem with things like GPL or AGPL is that you have to get really involved with license management. It also makes it harder for contributors as they also must adhere to the license. 

For now, I think we will consider switching to MPL2, but I'm not gonna go much farther.
