### ISSUE TITLE
Resources have no priority

### ISSUE THREAD

**Issue by UltraBlackLinux** [gaucho-matrero/altoclef#311]
## Steps to Reproduce (as best as you can)

join a server like zooh.minehut.gg and @get stone_axe

## Expected Behavior

It should get the widely available wooden planks

## Actual Behavior

It gets some of the veeery few oak logs, meaning it pathes for 4 minutes trying to get to the two oak logs to craft a crafting table and then axe

### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by JamesGreen31** [comment]
This is a very difficult problem to solve as the metric for "when to use planks" vs "when to use logs" isn't exactly simple. I'm sure we could maybe solve the issue with high level calculus, but it's not really worth it.
