### ISSUE TITLE
Less jittery camera movement (+ more natural camera movement)

### ISSUE THREAD

**Issue by BlockbenchUser** [gaucho-matrero/altoclef#317]
## Less Jittery Camera Movement
(The camera is VERY jittery, so it would be nice to smooth it out a little, and more natural camera movement so the players head doesn't immediately snap to the object it's interacting with)

### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by Dabaski** [comment]
https://github.com/JustaSqu1d/RenderSmoothing/releases/tag/v0.1-1.19.2 for 1.19.2
and https://github.com/scorbett123/RenderSmoothing/releases/tag/v0.1 for 1.18.2

**Comment by BlockbenchUser** [comment]
> https://github.com/JustaSqu1d/RenderSmoothing/releases/tag/v0.1-1.19.2 for 1.19.2 and https://github.com/scorbett123/RenderSmoothing/releases/tag/v0.1 for 1.18.2

K thanks for this
