### ISSUE TITLE
failed to set spawnpoint in @gamer when using non-english language

### ISSUE THREAD

**Issue by ditb3** [gaucho-matrero/altoclef#320]
## Steps to Reproduce (as best as you can)
1.Set a non-english language(I only tested French, Dennish, Chinese and Upsidedown English)
2.Use @gamer command
3.Waiting for the bot finishing several tasks until it is trying to set a spawnpoint before entering the End

## Expected Behavior
After clicking bed several times, the bot will enter the End portal

## Actual Behavior (What lead to the bot getting permanently stuck)
The bot continuously clicking the bed

## Other mods (if applicable)
lithium
phosphor
sodium
fabric api

### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by JamesGreen31** [comment]
As the large majority of our player base is English speaking, and because the work in this project is considerably slowed down, I am labeling this as *not fixing*. 

In the future, we may revisit this.
