### ISSUE TITLE
Complete crash

### ISSUE THREAD

**Issue by cripeer4046** [gaucho-matrero/altoclef#325]
Typing the command gamer

Game crash

Crash the game

## Crashlogs and Screenshots (if applicable)
_(you may drag + drop text logs and images here, thanks GitHub)_
Exit code:
The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'net.minecraft.class_6880 net.minecraft.class_638.method_23753(net.minecraft.class_2338)'

Fabric api

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.
a screen juste before the crash:
![1](https://user-images.githubusercontent.com/126106694/220732149-8b418410-9c07-4fb1-87e0-df733269053f.png)
[crash-2023-02-22_20.00.28-client.txt](https://github.com/gaucho-matrero/altoclef/files/10807432/crash-2023-02-22_20.00.28-client.txt)
Im on fabric 1.18 version

**Comment by JustaSqu1d** [comment]
Please upload the crash log.

**Comment by TheBlueBurger** [comment]
You seem to be using 1.18.2 altoclef with 1.18. Switch to 1.18.2

**Comment by cripeer4046** [comment]
> You seem to be using 1.18.2 altoclef with 1.18. Switch to 1.18.2

Worked, thanks you !
