### ISSUE TITLE
Game crashes when i do @gamer.

### ISSUE THREAD

**Issue by yeroc5311** [gaucho-matrero/altoclef#326]
## Steps to Reproduce (as best as you can) 
say @gamer

## Expected Behavior 
For it to beat the game

## Actual Behavior 
Crashes

## Crashlogs and Screenshots (if applicable)
YouTube video of the crash:https://youtu.be/uDECgVg5NuU

### Discord username (if you want updates)
yeroc5311#6618
### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by JustaSqu1d** [comment]
Crashlog?

**Comment by yeroc5311** [comment]
its somehow working on MultiMC the next day.
