### ISSUE TITLE
nightly download link is 404

### ISSUE THREAD

**Issue by patritha** [gaucho-matrero/altoclef#327]
## Your Idea
it would be cool it it worked

### Discord username (if you want updates)
Patritha🗿🗿🗿🗿🗿#1239
### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by JustaSqu1d** [comment]
Just use [Marvion's build](https://github.com/MarvionKirito/altoclef). It is much better in every single way.

**Comment by patritha** [comment]
ok i will

**Comment by patritha** [comment]
also is there a version for 1.19 and not 1.19.x

**Comment by JustaSqu1d** [comment]
Nope

**Comment by patritha** [comment]
aww
