### ISSUE TITLE
Update to 1.19.3 or 1.20 when it released and add the ability to get curtain places with elytra 

### ISSUE THREAD

**Issue by Bananalolok** [gaucho-matrero/altoclef#328]
### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by SylveonBottle** [comment]
> Literally already done on [Marvion's branch](https://github.com/MarvionKirito) and my fork on [Marvion's branch](https://github.com/JustaSqu1d/altoclef)

Is your fork 1.19.3? It appears to be missing e958ae27473beb441660f8d413aa4b2dc33de333

**Comment by pixo2000** [comment]
> Literally already done on [Marvion's branch](https://github.com/MarvionKirito) and my fork on [Marvion's branch](https://github.com/JustaSqu1d/altoclef)

There is no Update 1.20... I only play the newest update. if you can show me how i can update altoclef, i will do it myself
PS: Sorry for my Bad english.
