### ISSUE TITLE
@Survive command

### ISSUE THREAD

**Issue by NEWBOBBOY** [gaucho-matrero/altoclef#336]
## Your Idea
@survive command that made the bot do everything a normal player does like build a house or farm and loot and just overall try and survive you could do the building with schematics maybe I think someone else on the discord had a similar idea

### Discord username (if you want updates)
NEWBOBBOY#5430

### Developer Notes (leave this blank)

_Difficulty_: **___**
_Estimated Time Required_: **___**
Once development starts.

**Comment by NEWBOBBOY** [comment]
I think it might be a 7 out of 10 difficulty level

**Comment by hecker2000** [comment]
this seems possible, but schematics would have to be added...

**Comment by hecker2000** [comment]
> What like manually? because I would be fine with that

technically wurst has an auto bunker command, so I could see Altoclef using that small bunker to place chests in and farms near, the only problem is that Altoclef does not like traveling back to a deposit just for items. so while it would be cool, the bot just does not like having a base. I think there may be a workaround though, just make the bot go back to base before crafting anything but pickaxes. That would work (I think).

**Comment by JamesGreen31** [comment]
Alto is designed for speedrunning and while this is a great idea, its out of scope. Consider adding it yourself as this is a great task for a contributor.
