### ISSUE TITLE
light up area command

### ISSUE THREAD

**Issue by Nuclearpotato69** [gaucho-matrero/altoclef#345]

**Comment by johnnybpena1989** [comment]
I am on board with this idea. Also, for those that run with shaders and have a hard time seeing anything in the dark... just holding a torch in the offset hand will light up the area while mining. But the placement of torches would be such a huge help for cave mobs.

**Comment by JamesGreen31** [comment]
Alto doesn't really have a way to do this. I experimented with some ideas but its just not achievable in an intelgient way other than a hacky solution of placing torches near you. But to do it on the move? ... nah. This is a good idea for a contributor to play with though. Consider trying your hand at adding it!
