### ISSUE TITLE
.txt file for large command chains & custom functions

### ISSUE THREAD

**Issue by JJW836412** [gaucho-matrero/altoclef#348]
### Summery for suggestion:

The reason why this might be useful is because when I run your test command to get diamond armor, the bot keeps on dying from mobs (25 deaths so far and it hasn't touched a diamond) and it would be useful for the bot to prioritize getting more basic gear to increase its survival rate then go for the diamonds and netherite.

----------------------------------

Functions could look like

function1(command1; command2)

-------------------------------------
Format for a custom command "get basic resources" might be

getIronArmorFunction(get iron_helmet; get iron_chestplate; get iron_leggings; get iron_boots)

@basic-resource{getIronArmorFunction(); get torch 64; food 150; get oak_logs 64; get cobblestone 32}

---------------------------------------------

The getIronArmorFunction is an example function while the @basic-resource command is a custom runnable command.

-----------------------------------------------

### Developer Notes (leave this blank)

_Difficulty_: **4-6/10** (Idk how hard that is to add)
_Estimated Time Required_: **idk**
Once development starts.

**Comment by JustaSqu1d** [comment]
Already exists. See here for the [Alto Clef task creator](https://github.com/gaucho-matrero/Altoclef-TaskCreator).

I guess "Developer Notes _**(leave this blank)**_" wasn't clear enough.

**Comment by JamesGreen31** [comment]
See squid's comment.
