### ISSUE TITLE
Death chest

### ISSUE THREAD

**Issue by Nbtguyoriginal** [gaucho-matrero/altoclef#353]
## options to grab extra supplies as a sub task 
Extra supplies should be saved in a chest at current spawn point

### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by hecker2000** [comment]
that would be interesting, unfortunately, the bot does not have a "base" feature, it tends to go full nomad...

**Comment by JamesGreen31** [comment]
we could add this and it isn't a bad idea. However, it is designed for speed runs and speed runs do not need bases. This is a fun project for a contriuter, but not for maintainer. Consider forking the repository and trying your hand at adding this!
