### ISSUE TITLE
Efficiency issues in resource collection

### ISSUE THREAD

**Issue by TianmuTNT** [gaucho-matrero/altoclef#357]
## Your Idea
When it is excavating, it encounters minerals that need to be repeatedly collected and reused, and it always collects them multiple times, which greatly affects efficiency. For example, when making iron picks, barrels, and flints, it collects iron ore in stages.
### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by JamesGreen31** [comment]
this is part of pathfinding and unfortunately cannot be solved algorithmically. We tried, but this is not fixable.
