### ISSUE TITLE
The shaking of the perspective

### ISSUE THREAD

**Issue by TianmuTNT** [gaucho-matrero/altoclef#358]
## Your Idea
During use, the perspective always shakes, which is very detrimental to the player's visual experience.
### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by WireframeModel** [comment]
To fix this, type "#set randomlooking 0.0" & "#set randomlooking113 0.0"

**Comment by JamesGreen31** [comment]
# freelook false
