### ISSUE TITLE
Nightly link does not work

### ISSUE THREAD

**Issue by Philipou** [gaucho-matrero/altoclef#365]
## Your Idea
Make nightly link work by modifing something so it's no longer expired, build actions are all expired too

### Discord username (if you want updates)
philipou

### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by JamesGreen31** [comment]
Use marvion's fork for now. Vanilla alto will likely not move past 1.18.2
