### ISSUE TITLE
Porting to newer versions

### ISSUE THREAD

**Issue by Philipou** [gaucho-matrero/altoclef#366]
## Your Idea
Make the bot work on newer versions like 1.20.1

### Discord username (if you want updates)
philipou

### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by CheesyGuy110** [comment]
> ## Your Idea
> Make the bot work on newer versions like 1.20.1
> 
> ### Discord username (if you want updates)
> philipou, cheesyguy110
> 
> ### Developer Notes (leave this blank)
> _Difficulty_: **__** _Estimated Time Required_: **__** Once development starts.

**Comment by JamesGreen31** [comment]
Edit: #359 seems to be closed. Alto main will likely stay on 1.18.2 until I can update it. I don't plan on doing this soon though. See Marvion's fork.
