### ISSUE TITLE
IS THIS DEAD? PLEASE CONFIRM.

### ISSUE THREAD

**Issue by homelyseven250** [gaucho-matrero/altoclef#367]

**Comment by pyscripter99** [comment]
Development seems to be happening, but at a slow pace. Maybe in a few months this mod will be relevant again.

**Comment by milezero31** [comment]
> Development seems to be happening, but at a slow pace. Maybe in a few months this mod will be relevant again.

The mod is up to date and multiple great big fixes just happened. What do you expect based on your comment? Have you contributed?

**Comment by milezero31** [comment]
> Development seems to be happening, but at a slow pace. Maybe in a few months this mod will be relevant again.

Oh I thought this was on th3 Marvion fork. Go look a4 marvion fork

**Comment by Dabaski** [comment]
On the discord server I frequently update the FAQ message I've posted.

**Comment by luigi052005** [comment]
kinda dead

**Comment by JamesGreen31** [comment]
Marvion's fork is active. Main has been out of dev for some time. I do plan on reviving it, but until I have some time to really dive into it, its gonna be stale. Will likely review in 6 months.
