### ISSUE TITLE
scripting?

### ISSUE THREAD

**Issue by hecker2000** [gaucho-matrero/altoclef#370]
## Your Idea
it would be cool if it was possible to "script" some commands together, maybe it could look like the following:

set baseY = (random)
set baseX = (random)
DO
set randY = (random)
set randX = (random)
goto {randX} {randY}
get diamond 128
goto {baseX} {baseY}
stash {baseX + 10} {base + 10} 100 {baseX - 10} {baseY -10} 50 [diamond]
IF (idk some logic for if the bot knows it has over 200 diamonds) DO POINT2
LOOP
POINT2
test terminate
logoff

kinda pulling from random programming languages, but having a little scripting would allow for a lot more within alto clef!
even if just an API for alto clef was available then that would allow the bot to make much more intelligent.

### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by JamesGreen31** [comment]
Checkout altoclef task creator. I made a tool that does exactly this

**Comment by JamesGreen31** [comment]
https://github.com/gaucho-matrero/Altoclef-TaskCreator
