### ISSUE TITLE
Remove useless comments

### ISSUE THREAD

**Issue by KMatias123** [gaucho-matrero/altoclef#73]
Remove useless comments that don't provide any info related to how the code works

example of useless comment:
![image](https://user-images.githubusercontent.com/43719568/131486643-08547d1a-4b31-4fc9-b716-da57d950eced.png)

**Comment by adrisj7** [comment]
Removed my cringe in https://github.com/gaucho-matrero/altoclef/commit/c9a79176eecba1366179cb0437273c9049c1c5ff
