### ISSUE TITLE
Make variable and method names follow java naming conventions

### ISSUE THREAD

**Issue by KMatias123** [gaucho-matrero/altoclef#74]
method names should always start with lower case, and currently the project has upper case in some classes and lower case in others

[here](https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html) is a page i found about it, i didn't find anything updated in the last 20 years but it clearly says that methods should start with lower case and variables *should not* start with and underscore

**Comment by adrisj7** [comment]
the underscore part I have beef with >:(

but everything else is valid. Will address the issue with the arg/command system when I revamp/delete it
