### ISSUE TITLE
screws up crafting while getting things 

### ISSUE THREAD

**Issue by FiniteBench** [gaucho-matrero/altoclef#98]

**Comment by adrisj7** [comment]
Try adjusting the [`containerItemMoveDelay`](https://github.com/gaucho-matrero/altoclef/blob/5924db55e4d63a0a433f00272b7d35ea49b8116f/src/main/java/adris/altoclef/Settings.java#L66) setting to a larger value. Remember to run `@reload_settings` to apply your changes.

If that doesn't fix your issue you may reopen this. If so please give more info (are you running this on a server? What's the `containerItemMoveDelay` value you used? etc.)
